site_name: Designing Open Democracy
site_url: http://wiki.designingopendemocracy.com
theme:
  name: material
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - ezlinks:
      wikilinks: true