site_name: Designing Open Democracy
site_url: http://designingopendemocracy.com
repo_url: https://github.com/DesigningOpenDemocracy/DesigningOpenDemocracy.github.io
repo_name: DesigningOpenDemocracy/DesigningOpenDemocracy.github.io
theme:
  name: material
  logo: assets/dodlogo_transparent.png
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: slate
    primary: blue grey
    accent: indigo
extra_css:
  - assets/css/customizations.css
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
  - https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css
  - https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.Default.css
markdown_extensions:
  - footnotes
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - ezlinks:
      wikilinks: true
  - blog:
      post_excerpt: required
      archive: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - tags
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DesigningOpenDemocracy/DesigningOpenDemocracy.github.io
      name: Contribute on GitHub

hooks:
  - hooks/org_template.py

extra_javascript:
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
  - https://unpkg.com/leaflet.markercluster@1.5.3/dist/leaflet.markercluster.js
