site_name: Designing Open Democracy
site_url: http://designingopendemocracy.com
theme:
  name: material
  logo: assets/dodlogo_transparent.png
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.higlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  language: en
  palette:
    scheme: slate
    primary: blue grey
    accent: indigo
extra_css:
  - assets/css/customizations.css
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - ezlinks:
      wikilinks: true
  - blog:
      post_excerpt: required
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 


