#!/usr/bin/env python3
"""Regression tests for docs/assets/js/tz-country.js, the timezone -> country
table behind the "Just Australia?" filter suggestion on News and the Calendar
(docs/assets/js/country-suggest.js, generated by util/make_tz_countries.py).

A missing or wrong zone fails silently (the suggestion just never appears,
or offers the wrong country), so the zones this landscape's readers are most
likely to report are pinned here, including the legacy names some browsers
still return and zone.tab doesn't list.

    python -m unittest discover tests
"""

import json
import os
import re
import unittest

TABLE = os.path.join(os.path.dirname(__file__), "..", "docs", "assets", "js", "tz-country.js")


def load_table():
    with open(TABLE, encoding="utf-8") as f:
        m = re.search(r"window\.DOD_TZ_COUNTRY = (\{.*\});", f.read())
    return json.loads(m.group(1))


class TzCountryTableTests(unittest.TestCase):
    def setUp(self):
        self.table = load_table()

    def test_common_zones(self):
        for zone, cc in {
            "Australia/Sydney": "AU", "Australia/Melbourne": "AU", "Australia/Perth": "AU",
            "Pacific/Auckland": "NZ", "Asia/Taipei": "TW", "Europe/London": "GB",
            "America/New_York": "US", "Africa/Lagos": "NG", "Asia/Kolkata": "IN",
        }.items():
            with self.subTest(zone=zone):
                self.assertEqual(self.table.get(zone), cc)

    def test_legacy_names_browsers_still_report(self):
        for zone, cc in {"Asia/Calcutta": "IN", "Asia/Saigon": "VN", "Europe/Kiev": "UA",
                         "Australia/Canberra": "AU", "US/Eastern": "US"}.items():
            with self.subTest(zone=zone):
                self.assertEqual(self.table.get(zone), cc)

    def test_values_are_country_codes(self):
        bad = {z: c for z, c in self.table.items() if not re.fullmatch(r"[A-Z]{2}", c)}
        self.assertEqual(bad, {})

    def test_utc_is_not_a_country(self):
        # A UTC clock says nothing about where someone is; the script falls
        # back to the language setting instead.
        self.assertNotIn("UTC", self.table)
        self.assertNotIn("Etc/UTC", self.table)


if __name__ == "__main__":
    unittest.main()
