#!/usr/bin/env python3
"""
heartbeat_post.py — Scaffold and manage the monthly heartbeat draft

HEARTBEAT.md Step 6 has each run find-or-create this month's
docs/heartbeat/posts/YYYY-MM-sync.md, mirror its body into
docs/heartbeat/current.md, and — on the first run of the following month —
release it by dropping draft: true. This script automates the mechanical,
error-prone parts of that: typing the exact required frontmatter and
disclaimer block by hand (risk of drift — e.g. the disclaimer says "pushed
directly to main", which isn't always literally true the moment it's
written), and keeping current.md in sync.

It does NOT write the actual content (Landscape update / In the world /
Framework notes / What's next) — that's still a judgment call for whoever
(human or AI) is running the brief. This only handles the scaffold, the
mirror, and the release mechanics.

Usage:
    python util/heartbeat_post.py              # find-or-create this month's draft, report status
    python util/heartbeat_post.py --month 2026-07  # override the month label for a fresh draft
    python util/heartbeat_post.py --mirror      # sync current.md from the active draft's body
    python util/heartbeat_post.py --release     # drop draft: true, reset current.md (aborts if
                                                 # unresolved "<!-- tentative -->" markers remain)

Requirements: python-frontmatter (util/requirements.txt)
"""

import argparse
import glob
import os
import re
import sys
from datetime import date

try:
    import frontmatter
except ImportError:
    print("Missing dependency: pip install python-frontmatter")
    sys.exit(1)

DOCS_DIR = os.path.join(os.path.dirname(__file__), "..", "docs")
HEARTBEAT_DIR = os.path.join(DOCS_DIR, "heartbeat", "posts")
CURRENT_PATH = os.path.join(DOCS_DIR, "heartbeat", "current.md")
TODAY = date.today()

TENTATIVE_MARKER = "<!-- tentative: revisit next run -->"

# Verbatim from CLAUDE.md's "Heartbeat log" section. Do not edit this
# without updating CLAUDE.md too — they must stay in sync.
DISCLAIMER = (
    "> *This post was generated by Claude Code during a scheduled maintenance pass.\n"
    "> All statistics are derived from this wiki's own data. It was pushed directly\n"
    "> to main without prior human review — see HEARTBEAT.md for the trust model.\n"
    "> A human may review and amend it after the fact.*"
)

CURRENT_BANNER = (
    "# Current draft\n"
    "\n"
    "> **This is a live, unreleased work-in-progress.** It mirrors whatever this\n"
    "> month's [heartbeat](index.md) post is accumulating, updated after each\n"
    "> scheduled maintenance run. It lives outside `heartbeat/posts/` — the only\n"
    "> path the RSS/JSON feeds watch — so this page is never in a feed and\n"
    "> editing it never notifies subscribers. Treat anything below as unsettled:\n"
    "> it may change, grow, or be deleted before release. For finished posts, see\n"
    "> the [heartbeat log](index.md).\n"
)

CURRENT_PLACEHOLDER = (
    "*No draft is currently accumulating. Check back after the next scheduled\n"
    "heartbeat run.*\n"
)

DRAFT_RE = re.compile(r'^draft:\s*true\s*\n', re.MULTILINE)


def find_active_draft():
    """Return the path of the single draft: true post, or None. Errors if >1."""
    candidates = []
    for path in sorted(glob.glob(os.path.join(HEARTBEAT_DIR, "*-sync.md"))):
        post = frontmatter.load(path)
        if post.metadata.get("draft") is True:
            candidates.append(path)
    if len(candidates) > 1:
        print("More than one draft:true heartbeat post found — expected at most one:")
        for c in candidates:
            print(f"  {os.path.relpath(c)}")
        print("Resolve manually (release or delete the stale one) before continuing.")
        sys.exit(1)
    return candidates[0] if candidates else None


def month_label(override):
    if override:
        if not re.fullmatch(r"\d{4}-\d{2}", override):
            print(f"--month must be YYYY-MM, got: {override}")
            sys.exit(1)
        return override
    return TODAY.strftime("%Y-%m")


def create_draft(label):
    path = os.path.join(HEARTBEAT_DIR, f"{label}-sync.md")
    if os.path.exists(path):
        print(f"{os.path.relpath(path)} already exists — not overwriting.")
        sys.exit(1)
    content = f'''---
title: "Heartbeat sync — {label}"
date: {TODAY.isoformat()}
authors:
  - Claude
ai_generated: true
draft: true
categories:
  - Maintenance
tags:
  - landscape
summary: "TODO: one-sentence summary once this run's content is in."
---

TODO: one-sentence intro (current org/active/inactive/deregistered counts).

<!-- more -->

{DISCLAIMER}

## Landscape update

TODO: 2-3 sentences — current counts from stats.py, what was verified this
run, any status changes or notable findings.

## What's next

TODO: one sentence on which section of the landscape is oldest in the queue.
'''
    with open(path, "w") as f:
        f.write(content)
    return path


def extract_sections(draft_path):
    """Body content from the first '## ' heading onward (drops the teaser
    line, <!-- more -->, and disclaimer — current.md doesn't need those)."""
    post = frontmatter.load(draft_path)
    m = re.search(r"^##\s", post.content, re.MULTILINE)
    return post.content[m.start():].rstrip() + "\n" if m else post.content.rstrip() + "\n"


def mirror_to_current(draft_path):
    body = extract_sections(draft_path)
    with open(CURRENT_PATH, "w") as f:
        f.write(CURRENT_BANNER + "\n---\n\n" + body)
    print(f"Mirrored {os.path.relpath(draft_path)} -> {os.path.relpath(CURRENT_PATH)}")


def reset_current():
    with open(CURRENT_PATH, "w") as f:
        f.write(CURRENT_BANNER + "\n---\n\n" + CURRENT_PLACEHOLDER)
    print(f"Reset {os.path.relpath(CURRENT_PATH)} to placeholder.")


def release_draft(draft_path):
    with open(draft_path) as f:
        content = f.read()

    tentative_count = content.count(TENTATIVE_MARKER)
    if tentative_count:
        print(f"Refusing to release {os.path.relpath(draft_path)}: "
              f"{tentative_count} unresolved tentative item(s) remain.")
        print("Resolve each (confirm by removing the marker, or delete the item) first.")
        sys.exit(1)

    if not DRAFT_RE.search(content):
        print(f"{os.path.relpath(draft_path)} has no 'draft: true' line — already released?")
        sys.exit(1)

    new_content = DRAFT_RE.sub("", content, count=1)
    with open(draft_path, "w") as f:
        f.write(new_content)
    print(f"Released {os.path.relpath(draft_path)} (dropped draft: true).")

    reset_current()


def main():
    parser = argparse.ArgumentParser(description="Scaffold and manage the monthly heartbeat draft")
    parser.add_argument("--month", help="Month label (YYYY-MM) for a freshly created draft; "
                                         "defaults to the current month")
    parser.add_argument("--mirror", action="store_true",
                        help="Sync current.md from the active draft's body")
    parser.add_argument("--release", action="store_true",
                        help="Drop draft: true on the active draft and reset current.md")
    args = parser.parse_args()

    active = find_active_draft()

    if args.release:
        if not active:
            print("No active (draft: true) heartbeat post found — nothing to release.")
            sys.exit(1)
        release_draft(active)
        return

    created = False
    if not active:
        active = create_draft(month_label(args.month))
        created = True
        print(f"Created {os.path.relpath(active)}")

    if args.mirror:
        mirror_to_current(active)

    if not args.mirror or created:
        post = frontmatter.load(active)
        tentative_count = post.content.count(TENTATIVE_MARKER)
        print(f"Active draft: {os.path.relpath(active)}")
        print(f"  title: {post.metadata.get('title')}")
        print(f"  tags: {post.metadata.get('tags')}")
        if tentative_count:
            print(f"  ⚠ {tentative_count} unresolved tentative item(s) — must resolve before release")


if __name__ == "__main__":
    main()
