#!/usr/bin/env python3
"""
make_tz_countries.py — generate docs/assets/js/tz-country.js, the IANA
timezone → ISO 3166-1 country table the News and Calendar pages use to
suggest a country filter (docs/assets/js/country-suggest.js).

The browser reports its timezone without a network request or a permission
prompt (Intl.DateTimeFormat().resolvedOptions().timeZone), and nearly every
zone belongs to one country, so this is the privacy-respecting way to guess
where a reader is. The alternative, an IP-geolocation service, would send
every visitor's address to a third party.

Source is tzdata's zone.tab (one country per zone; zone1970.tab merges
countries that share a zone, which is no use here), plus LEGACY_ALIASES:
some browsers still report pre-2000s names such as Asia/Calcutta, which
zone.tab doesn't list. Run once and commit the output; the build never
reads zone.tab. Re-run only when tzdata adds zones worth knowing about.

    python util/make_tz_countries.py                          # /usr/share/zoneinfo/zone.tab
    python util/make_tz_countries.py --zonetab path/zone.tab
"""

import argparse
import json
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "docs", "assets", "js", "tz-country.js")

# Names from tzdata's `backward` file that browsers are known to return
# (Chrome reports ICU's canonical IDs, several of which are these), plus the
# old per-state/per-country aliases a system clock can still be set to.
LEGACY_ALIASES = {
    "Asia/Calcutta": "IN", "Asia/Saigon": "VN", "Asia/Katmandu": "NP",
    "Asia/Rangoon": "MM", "Asia/Dacca": "BD", "Asia/Ulan_Bator": "MN",
    "Asia/Thimbu": "BT", "Asia/Macao": "MO", "Asia/Ujung_Pandang": "ID",
    "Asia/Chongqing": "CN", "Asia/Chungking": "CN", "Asia/Harbin": "CN", "PRC": "CN",
    "ROC": "TW", "ROK": "KR", "Japan": "JP", "Singapore": "SG", "Hongkong": "HK",
    "Asia/Tel_Aviv": "IL", "Israel": "IL", "Iran": "IR", "Egypt": "EG", "Libya": "LY",
    "Asia/Istanbul": "TR", "Europe/Istanbul": "TR", "Turkey": "TR",
    "Europe/Kiev": "UA", "Europe/Belfast": "GB", "GB": "GB", "Eire": "IE",
    "Poland": "PL", "Portugal": "PT", "Iceland": "IS", "Atlantic/Faeroe": "FO",
    "America/Buenos_Aires": "AR", "America/Argentina/ComodRivadavia": "AR",
    "America/Indianapolis": "US", "America/Louisville": "US", "America/Fort_Wayne": "US",
    "America/Godthab": "GL", "America/Montreal": "CA", "America/Shiprock": "US",
    "Brazil/East": "BR", "Chile/Continental": "CL", "Cuba": "CU", "Jamaica": "JM",
    "Mexico/General": "MX", "Navajo": "US", "Pacific/Samoa": "AS", "Pacific/Truk": "FM",
    "Pacific/Ponape": "FM", "Pacific/Enderbury": "KI", "Africa/Asmera": "ER",
    "Africa/Timbuktu": "ML", "Kwajalein": "MH",
    "Australia/ACT": "AU", "Australia/Canberra": "AU", "Australia/NSW": "AU",
    "Australia/North": "AU", "Australia/Queensland": "AU", "Australia/South": "AU",
    "Australia/Tasmania": "AU", "Australia/Victoria": "AU", "Australia/West": "AU",
    "Australia/Yancowinna": "AU", "Australia/LHI": "AU",
    "NZ": "NZ", "NZ-CHAT": "NZ",
    "Canada/Atlantic": "CA", "Canada/Central": "CA", "Canada/Eastern": "CA",
    "Canada/Mountain": "CA", "Canada/Newfoundland": "CA", "Canada/Pacific": "CA",
    "US/Alaska": "US", "US/Arizona": "US", "US/Central": "US", "US/Eastern": "US",
    "US/Hawaii": "US", "US/Michigan": "US", "US/Mountain": "US", "US/Pacific": "US",
}


def read_zone_tab(path):
    table = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            table[parts[2]] = parts[0]
    return table


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--zonetab", default="/usr/share/zoneinfo/zone.tab")
    args = ap.parse_args()
    table = read_zone_tab(args.zonetab)
    for zone, cc in LEGACY_ALIASES.items():
        table.setdefault(zone, cc)
    body = json.dumps(dict(sorted(table.items())), separators=(",", ":"))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by util/make_tz_countries.py from tzdata's zone.tab; don't edit by hand.\n")
        f.write("// IANA timezone -> ISO 3166-1 alpha-2, for docs/assets/js/country-suggest.js.\n")
        f.write(f"window.DOD_TZ_COUNTRY = {body};\n")
    print(f"Wrote {len(table)} zones to {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
