#!/usr/bin/env python3
"""Generate the dotted world outline behind the home page's Democracy Map teaser.

Writes docs/overrides/partials/world-land-dots.html: a single SVG <path> made
of zero-length strokes, one per grid point that falls on land, which the
teaser's stroke-linecap: round draws as dots. Coordinates are plain degrees
(x = longitude, y = -latitude), so home.html places the real organisation and
blog-post dots in the same viewBox with no projection maths at all.

Only the land dots come from here; the org and post dots are drawn from
frontmatter at build time, so the teaser always shows where the Landscape
actually is. It deliberately carries no illustrative or placeholder pins: a
reader takes a pin on a map as a data point.

Source: Natural Earth 1:110m land (public domain), via the world-atlas npm
package's pre-built TopoJSON (ISC licence). Run once and commit the output;
the site build never fetches it, like everything else here.

    python util/make_world_dots.py                          # fetch land-110m.json from jsdelivr
    python util/make_world_dots.py --land land-110m.json    # use a local copy
    python util/make_world_dots.py --step 2.5               # coarser grid (degrees)
"""

import argparse
import json
import os
import sys
import urllib.request

LAND_URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "docs", "overrides", "partials", "world-land-dots.html")

# Latitude band drawn. Antarctica and the high Arctic would take a third of
# the height and hold no organisations; 76N keeps Iceland and Scandinavia,
# 58S keeps Tierra del Fuego. home.html's viewBox must match (-180 -76 360 134).
LAT_TOP = 76
LAT_BOTTOM = -58


def decode_arcs(topo):
    """TopoJSON arcs as absolute (lon, lat) lists (quantized, delta-encoded)."""
    (sx, sy), (tx, ty) = topo["transform"]["scale"], topo["transform"]["translate"]
    arcs = []
    for arc in topo["arcs"]:
        x = y = 0
        pts = []
        for dx, dy in arc:
            x += dx
            y += dy
            pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)
    return arcs


def ring(indices, arcs):
    """Stitch a ring from arc indices; ~i (negative) means arc i reversed."""
    pts = []
    for i in indices:
        arc = arcs[i] if i >= 0 else list(reversed(arcs[~i]))
        pts.extend(arc if not pts else arc[1:])  # shared joint point once
    return pts


def land_polygons(topo):
    """Every land polygon as a list of rings (outer first, then holes)."""
    arcs = decode_arcs(topo)
    polys = []
    for geom in topo["objects"]["land"]["geometries"]:
        coords = geom["arcs"] if geom["type"] == "MultiPolygon" else [geom["arcs"]]
        for poly in coords:
            polys.append([ring(r, arcs) for r in poly])
    return polys


def in_ring(lon, lat, pts):
    """Even-odd ray cast."""
    inside = False
    j = len(pts) - 1
    for i in range(len(pts)):
        xi, yi = pts[i]
        xj, yj = pts[j]
        if (yi > lat) != (yj > lat) and lon < (xj - xi) * (lat - yi) / (yj - yi) + xi:
            inside = not inside
        j = i
    return inside


def on_land(lon, lat, polys):
    for rings in polys:
        if in_ring(lon, lat, rings[0]) and not any(in_ring(lon, lat, h) for h in rings[1:]):
            return True
    return False


def fmt(n):
    return ("%.2f" % n).rstrip("0").rstrip(".")


def dot_path(polys, step):
    """Row by row, first dot absolute and the rest as relative moves, which
    keeps the path to a few bytes per dot."""
    parts = []
    lat = LAT_TOP - step / 2
    while lat > LAT_BOTTOM:
        prev = None
        lon = -180 + step / 2
        while lon < 180:
            if on_land(lon, lat, polys):
                if prev is None:
                    parts.append("M%s %sh0" % (fmt(lon), fmt(-lat)))
                else:
                    parts.append("m%s 0h0" % fmt(lon - prev))
                prev = lon
            lon += step
        lat -= step
    return "".join(parts)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--land", help="local land-110m.json (default: fetch %s)" % LAND_URL)
    ap.add_argument("--step", type=float, default=2.0, help="grid spacing in degrees (default 2)")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()

    if args.land:
        with open(args.land, encoding="utf-8") as f:
            topo = json.load(f)
    else:
        with urllib.request.urlopen(LAND_URL, timeout=30) as r:
            topo = json.load(r)

    d = dot_path(land_polygons(topo), args.step)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(
            "{#- Generated by util/make_world_dots.py (--step %s) from Natural Earth\n"
            "    1:110m land (public domain) via world-atlas (ISC). Do not edit by hand. -#}\n"
            '<path class="map-teaser-land" d="%s"/>\n' % (fmt(args.step), d)
        )
    print("wrote %s: %d dots, %d bytes" % (args.out, d.count("h0"), len(d)), file=sys.stderr)


if __name__ == "__main__":
    main()
